(define (indices->string board ixs)
  (list->string (map (ref board) (reverse ixs))))

(define (boggle board)
  (define (expand words)
    (define size (vector-length board))
    (define (on-board? xy)
      (and (< -1 (car xy) size)
           (< -1 (cdr xy) size)))
    (define (ok? word)
      (trie-prefix? (indices->string board word) *DICTIONARY*))
    (define (expand-word word)
      (filter-map (lambda (xy)
                    (and (on-board? xy)
                         (not (member xy word))
                         (ok? (cons xy word))
                         (cons xy word)))
                  (adj (car word))))
    (append-map expand-word words))
  (let walk ((ok (expand (expand ixs0))) (words '()))
    (if (null? ok)
        (let ()
          (define seen (make-hashtable string-hash string=?))
          (sort (lambda (A B)
                  (or (< (string-length A) (string-length B)) (string<? A B)))
                (filter-map (lambda (word)
                              (let ((word (indices->string board word)))
                                (and (trie-member? word *DICTIONARY*)
                                     (let ((ok (not (hashtable-ref seen word #f))))
                                       (hashtable-set! seen word #t) ok)
                                     word)))
                            words)))
        (walk (expand ok) (append ok words)))))
