
(define (nub words)
  (define seen (make-hashtable string-hash string=?))
  (define (seen!? word)
    (let ((yes/no (hashtable-ref seen word #f)))
      (hashtable-set! seen word #t)
      yes/no))
  (fold-right (lambda (word words)
                (if (not (seen!? word))
                    (cons word words)
                    words))
              '()
              words))
